# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ff5f844f5139419c4d704e37eb746d932f70ae238c80027e9092a10b9e26a57e43fa81d369b1621107bb910a183c68e529bead588ae4bf8fbc63477c6dfcb3d

test:
  secret_key_base: 326c216b09fecd1bd6ebec811350b4500390f36c8675c694a9e2ed47db926883b6c9981326ec6716f7135730ffc6ebb73a5d82c52d06de130cfdff8d752e2433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
